# Generated by Django 3.2.16 on 2023-02-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kouiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
    ]
